Us #12 suppression
houssembenali/fil_rouge pull request #41
Opened 2021-07-29 15:34 UTC by houssembenali

2021-07-29 15:43 UTC, houssembenali commented
Désoler les amis mais l'ajout du petit code Javascript 👻 et JQuerry 🎃 sont nécessaires pour gérer la partie de passation de paramétre entre les composants HTML (id et nom)

2021-08-02 10:14 UTC, AdrienCeschin requested changes
Certaines modifications peuvent être faites de suite (orthographe, code commenté, etc...), les autres commentaires sont ouverts à la discussion et peuvent être développés au cours d'un appel ou du daily.

2021-08-02 10:14 UTC, AdrienCeschin commented on docker/webapp/src/modules/projects/crud.py
> +    #reecrir fichier apres suppression ligne
Il pourrait être intéressant d'abstraire ces méthodes pour accéder (lire, supprimer, écrire) au fichier de la base de données, du module projects. Créer une classe utilitaire dans laquellle on trouverait des méthodes du genre "readprojectfile", "writeprojectfile", "updateprojectfile" permettrait de contrôler en un même endroit tous les accès au fichier de base de donnée (et de factoriser du code)

2021-08-02 10:14 UTC, AdrienCeschin commented on docker/webapp/src/modules/projects/crud.py
> +    return ''
Quel est l'intérêt de retourner une chaîne de caractères vide, a fortiori pour une méthode qui lorsqu'elle est appelée ne voit pas sa sortie utilisée ou stockée dans une variable ? Peut-être serait-il plus intéressant de retourner un code de sortie (0 si tout a bien fonctionné, 1 sinon, voire des codes plus précis en fonction de l'étape dans la méthode delete qui n'aurait pas fonctionné) et de se servir de ce retour pour modifier les valeurs des variables "errorMsg" et "msg" (cf commentaire sur la classe main).

2021-08-02 10:14 UTC, AdrienCeschin commented on docker/webapp/src/modules/projects/crud.py
> +        for row in reader:
Pourquoi ne pas sortir de cette boucle dès que la première occurrence de l'id est rencontrée ? Les id sont supposés être uniques donc aucun intérêt de poursuivre la boucle... Que se passe-t-il si au cours de cette boucle on rencontre plusieurs fois le même id, y a-t-il une gestion particulière du cas, des raisons de s'inquiéter de l'intégrité de la base de données ?

2021-08-02 10:14 UTC, AdrienCeschin commented on docker/webapp/src/modules/projects/crud.py
> +    return line_found
Si la ligne n'est pas trouvée on renvoie donc -1 ? Pourquoi ne pas se servir de ce retour pour tracer dans la méthode "delete" que le projet n'a pas pu être supprimé car il n'a pas été trouvé dans la base de données ?

2021-08-04 14:08 UTC, houssembenali commented on docker/webapp/src/modules/projects/crud.py
> +    #reecrir fichier apres suppression ligne
Abstraction faite dans le scripte utils.py

2021-08-04 14:09 UTC, houssembenali commented on docker/webapp/src/modules/projects/crud.py
> +    return ''
oui t'as tout a fait raison, un retour de message d'erreur a été ajouter et la méthode a été adapter a ça.

2021-08-04 14:11 UTC, houssembenali commented on docker/webapp/src/modules/projects/crud.py
> +        for row in reader:
c'est optimiser,
juste pour le cas de ID est impossible, lors de l'insertion on a un contrôle pour garantir a voir qu'un seul ID

2021-08-17 07:06 UTC, AdrienCeschin approved these changes

2021-08-17 17:04 UTC, merged